social
voshch/pedsim_ros pull request #2
Opened 2023-12-21 00:29 UTC by nhat-luu

have fun

2023-12-21 01:00 UTC, nhat-luu commented
@voshch

2023-12-21 07:51 UTC, voshch requested changes

2023-12-21 07:51 UTC, voshch commented on pedsim_agents/src/pedsim_agents/utils.py
> +class Thingy():
rename to something descriptive

2024-01-02 09:09 UTC, voshch commented
@nhat-luu

2024-02-22 17:32 UTC, closed without merging